### ISSUE TITLE
Brave Browser Artwork not Downloaded/Applied

### ISSUE THREAD

**Issue by RogueLikely** [ShadowBlip/crankshaft-flathub#4]
Artwork for the Brave Browser does exist on SteamGridDB but it's either not being downloaded or applied upon install via the plugin.

**Comment by fulfil-wedwards** [comment]
@RogueLikely This should be fixed now with the latest version of the plugin. Let me know if you experience any other issues!

**Comment by ShadowApex** [comment]
@RogueLikely This should be fixed in the latest version of the plugin. Let me know if you have any other issues!
